import { z } from 'zod'
import {
  KUN_USER_PAGE_TOPIC_TYPE,
  KUN_USER_PAGE_REPLY_TYPE,
  KUN_USER_PAGE_COMMENT_TYPE,
  KUN_USER_PAGE_GALGAME_TYPE,
  KUN_USER_PAGE_GALGAME_RESOURCE_TYPE
} from '~/constants/user'
